# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'dont-laugh-github-io'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About',   url: 'about.html'}
- {name: 'Blog', url: 'blog.html'}
- {name: 'Contact', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://www.github.com/Dont-laugh'}
- {icon: 'email',   link: '2387471378@qq.com'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: '你还可能感兴趣：'

post_date_prefix: 'Written on'
